// Commodity map — maps every Nepali commodity name to its English name,
// slug, unit, and category.
//
// Sources covered:
//   - kalimatimarket.gov.np  (Kalimati wholesale market)
//   - ampis.gov.np           (12 regional markets across Nepal)
//
// IMMUTABILITY RULE: slugs are generated once and never changed.
// If name_ne changes, update name_ne only — leave slug alone.
// If a commodity is retired, set active=false in the DB.

export type CommodityDef = {
  /** Canonical Nepali name stored in the DB */
  name_ne: string;
  name_en: string;
  slug: string;
  unit: "kg" | "dozen" | "piece" | "liter";
  category:
    | "vegetable"
    | "fruit"
    | "fish"
    | "meat"
    | "dairy"
    | "spice"
    | "leafy_green"
    | "mushroom"
    | "root_vegetable"
    | "legume"
    | "other";
};

export const COMMODITIES: CommodityDef[] = [
  // ─── VEGETABLE ────────────────────────────────────────────────────────────
  {
    name_ne: "गोलभेडा ठूलो(नेपाली)",
    name_en: "Tomato Big (Nepali)",
    slug: "tomato-big-nepali",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेडा सानो(टनेल)",
    name_en: "Tomato Small (Tunnel)",
    slug: "tomato-small-tunnel",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेडा सानो(लोकल)",
    name_en: "Tomato Small (Local)",
    slug: "tomato-small-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेडा ठूलो(हाइब्रिड)",
    name_en: "Tomato Big (Hybrid)",
    slug: "tomato-big-hybrid",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "आलु रातो(लाम्चो)",
    name_en: "Potato Red (Long)",
    slug: "potato-red-long",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "रातो आलु(गोलो)",
    name_en: "Potato Red (Round)",
    slug: "potato-red-round",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "आलु रातो(मुडे)",
    name_en: "Potato Red (Mude)",
    slug: "potato-red-mude",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "आलु रातो(भारतीय)",
    name_en: "Potato Red (Indian)",
    slug: "potato-red-indian",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "आलु सेतो",
    name_en: "Potato (White)",
    slug: "potato-white",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "प्याज सुकेको(नेपाली)",
    name_en: "Onion Dry (Nepali)",
    slug: "onion-dry-nepali",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "प्याज सुकेको (भारतीय)",
    name_en: "Onion Dry (Indian)",
    slug: "onion-dry-indian",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "काउली स्थानिय",
    name_en: "Cauliflower (Local)",
    slug: "cauliflower-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "काउली अर्काे",
    name_en: "Cauliflower (Other)",
    slug: "cauliflower-other",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "बन्दा(लोकल)",
    name_en: "Cabbage (Local)",
    slug: "cabbage-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "बोडी(तने)",
    name_en: "Yardlong Bean (Vine)",
    slug: "yardlong-bean-vine",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "बोडी खोले",
    name_en: "Yardlong Bean (Bush)",
    slug: "yardlong-bean-bush",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "मकै बोडी",
    name_en: "Corn Bean",
    slug: "corn-bean",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "मटरकोशा",
    name_en: "Green Peas",
    slug: "green-peas",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गाजर(लोकल)",
    name_en: "Carrot (Local)",
    slug: "carrot-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "मूला रातो",
    name_en: "Radish (Red)",
    slug: "radish-red",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सेतो मूला(हाइब्रीड)",
    name_en: "Radish White (Hybrid)",
    slug: "radish-white-hybrid",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "मूला सेतो",
    name_en: "Radish (White)",
    slug: "radish-white",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "भन्टा लाम्चो",
    name_en: "Eggplant (Long)",
    slug: "eggplant-long",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "भन्टा डल्लो",
    name_en: "Eggplant (Round)",
    slug: "eggplant-round",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "घिउ सिमी(लोकल)",
    name_en: "Butter Bean (Local)",
    slug: "butter-bean-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "घिउ सिमी(हाइब्रीड)",
    name_en: "Butter Bean (Hybrid)",
    slug: "butter-bean-hybrid",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "घिउ सिमी(राजमा)",
    name_en: "Butter Bean (Rajma)",
    slug: "butter-bean-rajma",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "टाटे सिमी",
    name_en: "Flat Bean",
    slug: "flat-bean",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "भटमासकोशा",
    name_en: "Edamame",
    slug: "edamame",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "तितो करेला",
    name_en: "Bitter Gourd",
    slug: "bitter-gourd",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "परवर(लोकल)",
    name_en: "Pointed Gourd (Local)",
    slug: "pointed-gourd-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "परवर(तराई)",
    name_en: "Pointed Gourd (Terai)",
    slug: "pointed-gourd-terai",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "लौका",
    name_en: "Bottle Gourd",
    slug: "bottle-gourd",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "चिचिण्डो",
    name_en: "Snake Gourd",
    slug: "snake-gourd",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "घिरौला",
    name_en: "Sponge Gourd",
    slug: "sponge-gourd",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "झिगूनी",
    name_en: "Zucchini",
    slug: "zucchini",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "फर्सी पाकेको",
    name_en: "Pumpkin (Ripe)",
    slug: "pumpkin-ripe",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "फर्सी हरियो(लाम्चो)",
    name_en: "Pumpkin Green (Long)",
    slug: "pumpkin-green-long",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "हरियो फर्सी(डल्लो)",
    name_en: "Pumpkin Green (Round)",
    slug: "pumpkin-green-round",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "भिण्डी",
    name_en: "Okra",
    slug: "okra",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सखरखण्ड",
    name_en: "Sweet Potato",
    slug: "sweet-potato",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "पिंडालू",
    name_en: "Taro",
    slug: "taro",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "स्कूस",
    name_en: "Chayote",
    slug: "chayote",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "रायो साग",
    name_en: "Mustard Greens",
    slug: "mustard-greens",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "पालूगो साग",
    name_en: "Spinach",
    slug: "spinach",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "चमसूरको साग",
    name_en: "Garden Cress",
    slug: "garden-cress",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "तोरीको साग",
    name_en: "Mustard Leaf",
    slug: "mustard-leaf",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "प्याज हरियो",
    name_en: "Spring Onion",
    slug: "spring-onion",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "च्याउ(कन्य)",
    name_en: "Mushroom (Button)",
    slug: "mushroom-button",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "च्याउ(डल्ले)",
    name_en: "Mushroom (Oyster)",
    slug: "mushroom-oyster",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "राजा च्याउ",
    name_en: "King Mushroom",
    slug: "mushroom-king",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सिताके च्याउ",
    name_en: "Shiitake Mushroom",
    slug: "mushroom-shiitake",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "कुरीलो",
    name_en: "Asparagus",
    slug: "asparagus",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "न्यूरो",
    name_en: "Fiddlehead Fern",
    slug: "fiddlehead-fern",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "ब्रोकाउली",
    name_en: "Broccoli",
    slug: "broccoli",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "चुकुन्दर",
    name_en: "Beetroot",
    slug: "beetroot",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सजिवन",
    name_en: "Moringa",
    slug: "moringa",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "रातो बन्दा",
    name_en: "Red Cabbage",
    slug: "red-cabbage",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "जिरीको साग",
    name_en: "Dill Leaf",
    slug: "dill-leaf",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सेलरी",
    name_en: "Celery",
    slug: "celery",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "पार्सले",
    name_en: "Parsley",
    slug: "parsley",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सौफको साग",
    name_en: "Fennel Greens",
    slug: "fennel-greens",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "पुदीना",
    name_en: "Mint",
    slug: "mint",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गान्टे मूला",
    name_en: "Turnip",
    slug: "turnip",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "इमली",
    name_en: "Tamarind",
    slug: "tamarind",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "तामा",
    name_en: "Bamboo Shoot",
    slug: "bamboo-shoot",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "तोफु",
    name_en: "Tofu",
    slug: "tofu",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गुन्दुक",
    name_en: "Gundruk",
    slug: "gundruk",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "अदुवा",
    name_en: "Ginger",
    slug: "ginger",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खु्र्सानी सुकेको",
    name_en: "Dried Chili",
    slug: "dried-chili",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो(लाम्चो)",
    name_en: "Green Chili (Long)",
    slug: "green-chili-long",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो(बुलेट)",
    name_en: "Green Chili (Bullet)",
    slug: "green-chili-bullet",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो(माछे)",
    name_en: "Green Chili (Mache)",
    slug: "green-chili-mache",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो(अकबरे)",
    name_en: "Green Chili (Akbare)",
    slug: "green-chili-akbare",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "भेडे खु्र्सानी",
    name_en: "Capsicum",
    slug: "capsicum",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "लसुन हरियो",
    name_en: "Garlic (Green)",
    slug: "garlic-green",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "हरियो धनिया",
    name_en: "Coriander Leaf",
    slug: "coriander-leaf",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "लसुन सुकेको चाइनिज",
    name_en: "Garlic Dry (Chinese)",
    slug: "garlic-dry-chinese",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "लसुन सुकेको नेपाली",
    name_en: "Garlic Dry (Nepali)",
    slug: "garlic-dry-nepali",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेंडा ठुलो (नेपाली)",
    name_en: "Tomato Thaulao  Nepali",
    slug: "tomato-thaulao-nepali",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेंडा ठुलो (भारतीय)",
    name_en: "Tomato Thaulao  Indian",
    slug: "tomato-thaulao-indian",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेंडा सानो (लोकल)",
    name_en: "Tomato Saanao  Local",
    slug: "tomato-saanao-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेंडा सानो (टनेल)",
    name_en: "Tomato Saanao Tanaela",
    slug: "tomato-saanao-tanaela",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेंडा सानो (भारतीय)",
    name_en: "Tomato Saanao  Indian",
    slug: "tomato-saanao-indian",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेंडा सानो (तराई)",
    name_en: "Tomato Saanao  Tarai",
    slug: "tomato-saanao-tarai",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "प्याज सुकेको (चाईनिज)",
    name_en: "Onion Dry  Chinese",
    slug: "onion-dry-chinese",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "प्याज सुकेको (नेपाली)",
    name_en: "Onion Dry  Nepali",
    slug: "onion-dry-nepali-1",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गाँजर (लोकल)",
    name_en: "Carrot  Local",
    slug: "carrot-local-1",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गाँजर (तराई)",
    name_en: "Carrot  Tarai",
    slug: "carrot-tarai",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गाँजर (नेपाली)",
    name_en: "Carrot  Nepali",
    slug: "carrot-nepali",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "बन्दा (लोकल)",
    name_en: "Cabbage  Local",
    slug: "cabbage-local-1",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "बन्दा (तराई)",
    name_en: "Cabbage  Tarai",
    slug: "cabbage-tarai",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "बन्दा (नरिवल)",
    name_en: "Cabbage Naraivala",
    slug: "cabbage-naraivala",
    unit: "piece",
    category: "vegetable",
  },
  {
    name_ne: "काउली (स्थानीय)",
    name_en: "Cauliflower Sathaanaiya",
    slug: "cauliflower-sathaanaiya",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "काउली स्थानीय (ज्यापू)",
    name_en: "Cauliflower Sathaanaiya Jayaapaoo",
    slug: "cauliflower-sathaanaiya-jayaapaoo",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "काउली (तराई)",
    name_en: "Cauliflower  Tarai",
    slug: "cauliflower-tarai",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "मूला सेतो (लोकल)",
    name_en: "Radish White  Local",
    slug: "radish-white-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "मूला सेतो (हाइब्रिड)",
    name_en: "Radish White  Hybrid",
    slug: "radish-white-hybrid-1",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "परवर (लोकल)",
    name_en: "Paravara  Local",
    slug: "paravara-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "परवर (तराई)",
    name_en: "Paravara  Tarai",
    slug: "paravara-tarai",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "घिरौंला",
    name_en: "Sponge_gourd",
    slug: "sponge-gourd-1",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "फर्सी हरियो (लाम्चो)",
    name_en: "Pumpkin Green  Long",
    slug: "pumpkin-green-long-1",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "फर्सी हरियो (डल्लो)",
    name_en: "Pumpkin Green  Round",
    slug: "pumpkin-green-round-1",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सलगम",
    name_en: "Salagama",
    slug: "salagama",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "बरेला",
    name_en: "Baraelaa",
    slug: "baraelaa",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "बन्दा रातो",
    name_en: "Cabbage Red",
    slug: "cabbage-red",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "ग्याठ कोबी",
    name_en: "Gayaatha Kaobai",
    slug: "gayaatha-kaobai",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "हरियो मकै",
    name_en: "Green Makaai",
    slug: "green-makaai",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गुन्द्रुक",
    name_en: "Gaunadarauka",
    slug: "gaunadarauka",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "रुख टमाटर",
    name_en: "Raukha Tomato",
    slug: "raukha-tomato",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो (लाम्चो)",
    name_en: "Chili Green  Long",
    slug: "chili-green-long",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो (बुलेट)",
    name_en: "Chili Green Baulaeta",
    slug: "chili-green-baulaeta",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो (माछे)",
    name_en: "Chili Green Maachhae",
    slug: "chili-green-maachhae",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो (अकबरे)",
    name_en: "Chili Green अkabarae",
    slug: "chili-green-kabarae",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सुकेको छ्यापी",
    name_en: "Dry Chhayaapai",
    slug: "dry-chhayaapai",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "हरियो छ्यापी",
    name_en: "Green Chhayaapai",
    slug: "green-chhayaapai",
    unit: "kg",
    category: "vegetable",
  },
  // ─── FRUIT ────────────────────────────────────────────────────────────
  {
    name_ne: "स्याउ(फूजी)",
    name_en: "Apple (Fuji)",
    slug: "apple-fuji",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "केरा(नेपाली)",
    name_en: "Banana (Nepali)",
    slug: "banana-nepali",
    unit: "dozen",
    category: "fruit",
  },
  {
    name_ne: "केरा(मालभोग)",
    name_en: "Banana (Malbhog)",
    slug: "banana-malbhog",
    unit: "dozen",
    category: "fruit",
  },
  {
    name_ne: "कागती",
    name_en: "Lime",
    slug: "lime",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "अनार",
    name_en: "Pomegranate",
    slug: "pomegranate",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "आँप(मालदह)",
    name_en: "Mango (Malda)",
    slug: "mango-malda",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "आँप(दसहरी)",
    name_en: "Mango (Dashehari)",
    slug: "mango-dashehari",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "तरबुजा(हरियो)",
    name_en: "Watermelon (Green)",
    slug: "watermelon-green",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "जुनार",
    name_en: "Mandarin Orange",
    slug: "mandarin-orange",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "भुई कटहर",
    name_en: "Jackfruit (Ground)",
    slug: "jackfruit-ground",
    unit: "piece",
    category: "fruit",
  },
  {
    name_ne: "काक्रो(लोकल)",
    name_en: "Cucumber (Local)",
    slug: "cucumber-local",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "काक्रो(हाइब्रीड)",
    name_en: "Cucumber (Hybrid)",
    slug: "cucumber-hybrid",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "काक्रो(लोकलक्रस)",
    name_en: "Cucumber (Local Cross)",
    slug: "cucumber-local-cross",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "रुख कटहर",
    name_en: "Jackfruit (Tree)",
    slug: "jackfruit-tree",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "नासपाती(चाइनिज)",
    name_en: "Pear (Chinese)",
    slug: "pear-chinese",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "मेवा(नेपाली)",
    name_en: "Papaya (Nepali)",
    slug: "papaya-nepali",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "मेवा(भारतीय)",
    name_en: "Papaya (Indian)",
    slug: "papaya-indian",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "लीच्ची(लोकल)",
    name_en: "Lychee (Local)",
    slug: "lychee-local",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "लीच्ची(भारतीय)",
    name_en: "Lychee (Indian)",
    slug: "lychee-indian",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "नरिवल(काँचो)",
    name_en: "Coconut (Raw)",
    slug: "coconut-raw",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "नरिवल(हरियो)",
    name_en: "Coconut (Green)",
    slug: "coconut-green",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "चुकन्दर",
    name_en: "Chaukanadara",
    slug: "chaukanadara",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "स्याउ (झोले)",
    name_en: "Apple Jhaolae",
    slug: "apple-jhaolae",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "स्याउ (फूजी)",
    name_en: "Apple Phaoojai",
    slug: "apple-phaoojai",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "स्याउ (मुस्ताङ्ग)",
    name_en: "Apple Mausataangaga",
    slug: "apple-mausataangaga",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "स्याउ (जुम्ला)",
    name_en: "Apple Jaumalaa",
    slug: "apple-jaumalaa",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "स्याउ (चकलेटी)",
    name_en: "Apple Chakalaetai",
    slug: "apple-chakalaetai",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "केरा (नेपाली)",
    name_en: "Banana  Nepali",
    slug: "banana-nepali-1",
    unit: "dozen",
    category: "fruit",
  },
  {
    name_ne: "केरा (मालभोग)",
    name_en: "Banana Maalabhaoga",
    slug: "banana-maalabhaoga",
    unit: "dozen",
    category: "fruit",
  },
  {
    name_ne: "केरा (हरियो)",
    name_en: "Banana  Green",
    slug: "banana-green",
    unit: "dozen",
    category: "fruit",
  },
  {
    name_ne: "केरा (भारतीय)",
    name_en: "Banana  Indian",
    slug: "banana-indian",
    unit: "dozen",
    category: "fruit",
  },
  {
    name_ne: "आँप (मालदह)",
    name_en: "आnpa Maaladaha",
    slug: "npa-maaladaha",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "आँप (दसहरी)",
    name_en: "आnpa Dasaharai",
    slug: "npa-dasaharai",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "आँप (चौसा)",
    name_en: "आnpa Chaausaa",
    slug: "npa-chaausaa",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "आँप (कलकत्ते)",
    name_en: "आnpa Kalakatatae",
    slug: "npa-kalakatatae",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "आँप (बम्बे)",
    name_en: "आnpa Bamabae",
    slug: "npa-bamabae",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "अंगुर (हरियो)",
    name_en: "Grapes  Green",
    slug: "grapes-green",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "अंगुर (कालो)",
    name_en: "Grapes Kaalao",
    slug: "grapes-kaalao",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "सुन्तला (नेपाली)",
    name_en: "Orange  Nepali",
    slug: "orange-nepali",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "सुन्तला (भारतीय)",
    name_en: "Orange  Indian",
    slug: "orange-indian",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "तर्बुजा (हरियो)",
    name_en: "Tarabaujaa  Green",
    slug: "tarabaujaa-green",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "तर्बुजा (पाटे)",
    name_en: "Tarabaujaa Paatae",
    slug: "tarabaujaa-paatae",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "मौसम",
    name_en: "Maausama",
    slug: "maausama",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "भुँईकटहर",
    name_en: "Bhaunईkatahara",
    slug: "bhaun-katahara",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "काँक्रो (लोकल)",
    name_en: "Cucumber  Local",
    slug: "cucumber-local-1",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "काँक्रो (हाइब्रिड)",
    name_en: "Cucumber  Hybrid",
    slug: "cucumber-hybrid-1",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "काँक्रो (स्थानीय क्रस)",
    name_en: "Cucumber Sathaanaiya Karasa",
    slug: "cucumber-sathaanaiya-karasa",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "निबुवा",
    name_en: "Naibauvaa",
    slug: "naibauvaa",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "चाक्सी",
    name_en: "Chaakasai",
    slug: "chaakasai",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "नास्पाती (लोकल)",
    name_en: "Naasapaatai  Local",
    slug: "naasapaatai-local",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "नास्पाती (चाईनिज)",
    name_en: "Naasapaatai  Chinese",
    slug: "naasapaatai-chinese",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "मेवा (नेपाली)",
    name_en: "Papaya  Nepali",
    slug: "papaya-nepali-1",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "मेवा (भारतीय)",
    name_en: "Papaya  Indian",
    slug: "papaya-indian-1",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "अम्बा",
    name_en: "अmabaa",
    slug: "mabaa",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "लप्सी",
    name_en: "Lapasai",
    slug: "lapasai",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "लिच्ची (लोकल)",
    name_en: "Laichachai  Local",
    slug: "laichachai-local",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "लिच्ची (भारतीय)",
    name_en: "Laichachai  Indian",
    slug: "laichachai-indian",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "खर्बुजा",
    name_en: "Kharabaujaa",
    slug: "kharabaujaa",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "उखु",
    name_en: "उkhau",
    slug: "khau",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "किनु",
    name_en: "Kainau",
    slug: "kainau",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "स्ट्रबेरी",
    name_en: "Satarabaerai",
    slug: "satarabaerai",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "किवि",
    name_en: "Kaivai",
    slug: "kaivai",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "शरीफा",
    name_en: "Sharaiphaa",
    slug: "sharaiphaa",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "आभोकाडो",
    name_en: "आbhaokaadao",
    slug: "bhaokaadao",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "अमला",
    name_en: "अmalaa",
    slug: "malaa",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "नरिवल (काँचो)",
    name_en: "Naraivala Kaanchao",
    slug: "naraivala-kaanchao",
    unit: "piece",
    category: "fruit",
  },
  {
    name_ne: "नरिवल (हरियो)",
    name_en: "Naraivala  Green",
    slug: "naraivala-green",
    unit: "piece",
    category: "fruit",
  },
  {
    name_ne: "ड्रागन फ्रुट (नेपाली)",
    name_en: "Daraagana Pharauta  Nepali",
    slug: "daraagana-pharauta-nepali",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "ड्रागन फ्रुट (भारतीय)",
    name_en: "Daraagana Pharauta  Indian",
    slug: "daraagana-pharauta-indian",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "बयर (नेपाली)",
    name_en: "Bayara  Nepali",
    slug: "bayara-nepali",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "बयर (भारतीय)",
    name_en: "Bayara  Indian",
    slug: "bayara-indian",
    unit: "kg",
    category: "fruit",
  },
  // ─── SPICE ────────────────────────────────────────────────────────────
  {
    name_ne: "सुकेको खुर्सानी",
    name_en: "Dry Chili",
    slug: "dry-chili",
    unit: "kg",
    category: "spice",
  },
  {
    name_ne: "भेडे खुर्सानी",
    name_en: "Bhaedae Chili",
    slug: "bhaedae-chili",
    unit: "kg",
    category: "spice",
  },
  {
    name_ne: "हरियो लसुन",
    name_en: "Green Garlic",
    slug: "green-garlic",
    unit: "kg",
    category: "spice",
  },
  {
    name_ne: "सुकेको चाईनिज लसुन",
    name_en: "Dry Chinese Garlic",
    slug: "dry-chinese-garlic",
    unit: "kg",
    category: "spice",
  },
  {
    name_ne: "सुकेको नेपाली लसुन",
    name_en: "Dry Nepali Garlic",
    slug: "dry-nepali-garlic",
    unit: "kg",
    category: "spice",
  },
  {
    name_ne: "सुकेको लसुन (भारतीय)",
    name_en: "Dry Garlic  Indian",
    slug: "dry-garlic-indian",
    unit: "kg",
    category: "spice",
  },
  {
    name_ne: "मरिच",
    name_en: "Maraicha",
    slug: "maraicha",
    unit: "kg",
    category: "spice",
  },
  {
    name_ne: "सुकमेल",
    name_en: "Saukamaela",
    slug: "saukamaela",
    unit: "kg",
    category: "spice",
  },
  {
    name_ne: "अलैँची",
    name_en: "अlaainchai",
    slug: "laainchai",
    unit: "kg",
    category: "spice",
  },
  {
    name_ne: "जिरा",
    name_en: "Jairaa",
    slug: "jairaa",
    unit: "kg",
    category: "spice",
  },
  // ─── LEAFY_GREEN ────────────────────────────────────────────────────────────
  {
    name_ne: "पालुंगो साग",
    name_en: "Paalaungao Greens",
    slug: "paalaungao-greens",
    unit: "kg",
    category: "leafy_green",
  },
  {
    name_ne: "चम्सुरको साग",
    name_en: "Chamasaurakao Greens",
    slug: "chamasaurakao-greens",
    unit: "kg",
    category: "leafy_green",
  },
  {
    name_ne: "मेथीको साग",
    name_en: "Maethaikao Greens",
    slug: "maethaikao-greens",
    unit: "kg",
    category: "leafy_green",
  },
  {
    name_ne: "कोइरालो",
    name_en: "Koiralo",
    slug: "koiralo",
    unit: "kg",
    category: "leafy_green",
  },
  {
    name_ne: "पुदिना",
    name_en: "Paudainaa",
    slug: "paudainaa",
    unit: "kg",
    category: "leafy_green",
  },
  // ─── MUSHROOM ────────────────────────────────────────────────────────────
  {
    name_ne: "च्याउ (कन्ये)",
    name_en: "Mushroom Kanayae",
    slug: "mushroom-kanayae",
    unit: "kg",
    category: "mushroom",
  },
  {
    name_ne: "च्याउ (डल्ले)",
    name_en: "Mushroom Dalalae",
    slug: "mushroom-dalalae",
    unit: "kg",
    category: "mushroom",
  },
  // ─── ROOT_VEGETABLE ────────────────────────────────────────────────────────────
  {
    name_ne: "रातो आलु (लाम्चो)",
    name_en: "Red Potato  Long",
    slug: "red-potato-long",
    unit: "kg",
    category: "root_vegetable",
  },
  {
    name_ne: "रातो आलु (गोलो)",
    name_en: "Red Potato Gaolao",
    slug: "red-potato-gaolao",
    unit: "kg",
    category: "root_vegetable",
  },
  {
    name_ne: "आलु रातो (मुढे)",
    name_en: "Potato Red Maudhae",
    slug: "potato-red-maudhae",
    unit: "kg",
    category: "root_vegetable",
  },
  {
    name_ne: "आलु रातो (भारतीय)",
    name_en: "Potato Red  Indian",
    slug: "potato-red-indian-1",
    unit: "kg",
    category: "root_vegetable",
  },
  {
    name_ne: "पिंडालु",
    name_en: "Paindaalau",
    slug: "paindaalau",
    unit: "kg",
    category: "root_vegetable",
  },
  {
    name_ne: "तरुल",
    name_en: "Taraula",
    slug: "taraula",
    unit: "kg",
    category: "root_vegetable",
  },
  // ─── LEGUME ────────────────────────────────────────────────────────────
  {
    name_ne: "बोडी (तने)",
    name_en: "Cowpea Tanae",
    slug: "cowpea-tanae",
    unit: "kg",
    category: "legume",
  },
  {
    name_ne: "बोडी (रातो)",
    name_en: "Cowpea  Red",
    slug: "cowpea-red",
    unit: "kg",
    category: "legume",
  },
  {
    name_ne: "घिउ सिमी (लोकल)",
    name_en: "Ghaiउ Beans  Local",
    slug: "ghai-beans-local",
    unit: "kg",
    category: "legume",
  },
  {
    name_ne: "घिउ सिमी (हाइब्रिड)",
    name_en: "Ghaiउ Beans  Hybrid",
    slug: "ghai-beans-hybrid",
    unit: "kg",
    category: "legume",
  },
  {
    name_ne: "घिउ सिमी (राजमा)",
    name_en: "Ghaiउ Beans Raajamaa",
    slug: "ghai-beans-raajamaa",
    unit: "kg",
    category: "legume",
  },
  {
    name_ne: "भटमास",
    name_en: "Bhatamaasa",
    slug: "bhatamaasa",
    unit: "kg",
    category: "legume",
  },
  {
    name_ne: "बकुला",
    name_en: "Bakaulaa",
    slug: "bakaulaa",
    unit: "kg",
    category: "legume",
  },
  // ─── FISH ────────────────────────────────────────────────────────────
  {
    name_ne: "माछा सुकेको",
    name_en: "Dried Fish",
    slug: "fish-dried",
    unit: "kg",
    category: "fish",
  },
  {
    name_ne: "ताजा माछा(रहु)",
    name_en: "Fresh Fish (Rohu)",
    slug: "fish-rohu",
    unit: "kg",
    category: "fish",
  },
  {
    name_ne: "ताजा माछा(बचुवा)",
    name_en: "Fresh Fish (Bachwa)",
    slug: "fish-bachwa",
    unit: "kg",
    category: "fish",
  },
  {
    name_ne: "ताजा माछा(छडी)",
    name_en: "Fresh Fish (Chhadi)",
    slug: "fish-chhadi",
    unit: "kg",
    category: "fish",
  },
  {
    name_ne: "सुकेको माछा",
    name_en: "Dry Fish",
    slug: "dry-fish",
    unit: "kg",
    category: "fish",
  },
  {
    name_ne: "ताजा माछा (रहु)",
    name_en: "Fresh Fish Rahau",
    slug: "fresh-fish-rahau",
    unit: "kg",
    category: "fish",
  },
  {
    name_ne: "ताजा माछा (बचुवा)",
    name_en: "Fresh Fish Bachauvaa",
    slug: "fresh-fish-bachauvaa",
    unit: "kg",
    category: "fish",
  },
  {
    name_ne: "ताजा माछा (छडी)",
    name_en: "Fresh Fish Chhadai",
    slug: "fresh-fish-chhadai",
    unit: "kg",
    category: "fish",
  },
  // ─── MEAT ────────────────────────────────────────────────────────────
  {
    name_ne: "कुखुराको मासु (बोईलर)",
    name_en: "Chicken Meat Baoईlara",
    slug: "chicken-meat-bao-lara",
    unit: "kg",
    category: "meat",
  },
  {
    name_ne: "कुखुराको मासु (लोकल)",
    name_en: "Chicken Meat  Local",
    slug: "chicken-meat-local",
    unit: "kg",
    category: "meat",
  },
  {
    name_ne: "खसीको मासु",
    name_en: "Mutton Meat",
    slug: "mutton-meat",
    unit: "kg",
    category: "meat",
  },
  {
    name_ne: "बंगुरको मासु",
    name_en: "Pork Meat",
    slug: "pork-meat",
    unit: "kg",
    category: "meat",
  },
  // ─── DAIRY ────────────────────────────────────────────────────────────
  {
    name_ne: "गाईको दुध",
    name_en: "Cow_s Milk",
    slug: "cow-s-milk",
    unit: "liter",
    category: "dairy",
  },
  {
    name_ne: "भैसीको दुध",
    name_en: "Buffalo_s Milk",
    slug: "buffalo-s-milk",
    unit: "liter",
    category: "dairy",
  },
  {
    name_ne: "घ्यु",
    name_en: "Ghee",
    slug: "ghee",
    unit: "liter",
    category: "dairy",
  },
  {
    name_ne: "पनीर",
    name_en: "Paneer",
    slug: "paneer",
    unit: "liter",
    category: "dairy",
  },
  {
    name_ne: "छुर्पी",
    name_en: "Chhaurapai",
    slug: "chhaurapai",
    unit: "liter",
    category: "dairy",
  },
  {
    name_ne: "मखन",
    name_en: "Makhana",
    slug: "makhana",
    unit: "liter",
    category: "dairy",
  },
];

// ─── Build a lookup map: cleaned Nepali name → CommodityDef ─────────────────
// Used by the scraper to match incoming names from the HTML table.
export const COMMODITY_MAP = new Map<string, CommodityDef>(
  COMMODITIES.map((c) => [c.name_ne, c])
);

// ─── Quick invariant check (runs at module load, not at runtime) ─────────────
if (process.env.NODE_ENV !== "production") {
  const slugs = COMMODITIES.map((c) => c.slug);
  const uniqueSlugs = new Set(slugs);
  if (uniqueSlugs.size !== slugs.length) {
    throw new Error("commodityMap: duplicate slugs detected — fix immediately");
  }
  const names = COMMODITIES.map((c) => c.name_ne);
  const uniqueNames = new Set(names);
  if (uniqueNames.size !== names.length) {
    throw new Error(
      "commodityMap: duplicate name_ne entries detected — fix immediately"
    );
  }
}
