// Commodity map — maps every Nepali commodity name (exactly as it appears
// in the Kalimati market HTML table, after stripping the unit suffix) to its
// English name, slug, unit, and category.
//
// IMMUTABILITY RULE: slugs are generated once and never changed.
// If a name_ne changes, update name_ne only — leave slug alone.
// If a commodity is retired, set active=false in the DB; don't reuse the slug.
//
// Validated against the live kalimatimarket.gov.np/price table (June 2026).

export type CommodityDef = {
  /** Exact Nepali name as it appears in the Kalimati table (after stripping unit suffix) */
  name_ne: string;
  name_en: string;
  slug: string;
  unit: "kg" | "dozen" | "piece";
  category: "vegetable" | "fruit" | "fish";
};

export const COMMODITIES: CommodityDef[] = [
  // ─── Vegetables ────────────────────────────────────────────────────────────
  {
    name_ne: "गोलभेडा ठूलो(नेपाली)",
    name_en: "Tomato Big (Nepali)",
    slug: "tomato-big-nepali",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेडा सानो(टनेल)",
    name_en: "Tomato Small (Tunnel)",
    slug: "tomato-small-tunnel",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेडा सानो(लोकल)",
    name_en: "Tomato Small (Local)",
    slug: "tomato-small-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गोलभेडा ठूलो(हाइब्रिड)",
    name_en: "Tomato Big (Hybrid)",
    slug: "tomato-big-hybrid",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "आलु रातो(लाम्चो)",
    name_en: "Potato Red (Long)",
    slug: "potato-red-long",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "रातो आलु(गोलो)",
    name_en: "Potato Red (Round)",
    slug: "potato-red-round",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "आलु रातो(मुडे)",
    name_en: "Potato Red (Mude)",
    slug: "potato-red-mude",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "आलु रातो(भारतीय)",
    name_en: "Potato Red (Indian)",
    slug: "potato-red-indian",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "आलु सेतो",
    name_en: "Potato (White)",
    slug: "potato-white",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "प्याज सुकेको(नेपाली)",
    name_en: "Onion Dry (Nepali)",
    slug: "onion-dry-nepali",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "प्याज सुकेको (भारतीय)",
    name_en: "Onion Dry (Indian)",
    slug: "onion-dry-indian",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "काउली स्थानिय",
    name_en: "Cauliflower (Local)",
    slug: "cauliflower-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "काउली अर्काे",
    name_en: "Cauliflower (Other)",
    slug: "cauliflower-other",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "बन्दा(लोकल)",
    name_en: "Cabbage (Local)",
    slug: "cabbage-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "बोडी(तने)",
    name_en: "Yardlong Bean (Vine)",
    slug: "yardlong-bean-vine",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "बोडी खोले",
    name_en: "Yardlong Bean (Bush)",
    slug: "yardlong-bean-bush",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "मकै बोडी",
    name_en: "Corn Bean",
    slug: "corn-bean",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "मटरकोशा",
    name_en: "Green Peas",
    slug: "green-peas",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गाजर(लोकल)",
    name_en: "Carrot (Local)",
    slug: "carrot-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "मूला रातो",
    name_en: "Radish (Red)",
    slug: "radish-red",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सेतो मूला(हाइब्रीड)",
    name_en: "Radish White (Hybrid)",
    slug: "radish-white-hybrid",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "मूला सेतो",
    name_en: "Radish (White)",
    slug: "radish-white",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "भन्टा लाम्चो",
    name_en: "Eggplant (Long)",
    slug: "eggplant-long",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "भन्टा डल्लो",
    name_en: "Eggplant (Round)",
    slug: "eggplant-round",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "घिउ सिमी(लोकल)",
    name_en: "Butter Bean (Local)",
    slug: "butter-bean-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "घिउ सिमी(हाइब्रीड)",
    name_en: "Butter Bean (Hybrid)",
    slug: "butter-bean-hybrid",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "घिउ सिमी(राजमा)",
    name_en: "Butter Bean (Rajma)",
    slug: "butter-bean-rajma",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "टाटे सिमी",
    name_en: "Flat Bean",
    slug: "flat-bean",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "भटमासकोशा",
    name_en: "Edamame",
    slug: "edamame",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "तितो करेला",
    name_en: "Bitter Gourd",
    slug: "bitter-gourd",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "परवर(लोकल)",
    name_en: "Pointed Gourd (Local)",
    slug: "pointed-gourd-local",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "परवर(तराई)",
    name_en: "Pointed Gourd (Terai)",
    slug: "pointed-gourd-terai",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "लौका",
    name_en: "Bottle Gourd",
    slug: "bottle-gourd",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "चिचिण्डो",
    name_en: "Snake Gourd",
    slug: "snake-gourd",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "घिरौला",
    name_en: "Sponge Gourd",
    slug: "sponge-gourd",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "झिगूनी",
    name_en: "Zucchini",
    slug: "zucchini",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "फर्सी पाकेको",
    name_en: "Pumpkin (Ripe)",
    slug: "pumpkin-ripe",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "फर्सी हरियो(लाम्चो)",
    name_en: "Pumpkin Green (Long)",
    slug: "pumpkin-green-long",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "हरियो फर्सी(डल्लो)",
    name_en: "Pumpkin Green (Round)",
    slug: "pumpkin-green-round",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "भिण्डी",
    name_en: "Okra",
    slug: "okra",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सखरखण्ड",
    name_en: "Sweet Potato",
    slug: "sweet-potato",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "पिंडालू",
    name_en: "Taro",
    slug: "taro",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "स्कूस",
    name_en: "Chayote",
    slug: "chayote",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "रायो साग",
    name_en: "Mustard Greens",
    slug: "mustard-greens",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "पालूगो साग",
    name_en: "Spinach",
    slug: "spinach",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "चमसूरको साग",
    name_en: "Garden Cress",
    slug: "garden-cress",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "तोरीको साग",
    name_en: "Mustard Leaf",
    slug: "mustard-leaf",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "प्याज हरियो",
    name_en: "Spring Onion",
    slug: "spring-onion",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "च्याउ(कन्य)",
    name_en: "Mushroom (Button)",
    slug: "mushroom-button",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "च्याउ(डल्ले)",
    name_en: "Mushroom (Oyster)",
    slug: "mushroom-oyster",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "राजा च्याउ",
    name_en: "King Mushroom",
    slug: "mushroom-king",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सिताके च्याउ",
    name_en: "Shiitake Mushroom",
    slug: "mushroom-shiitake",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "कुरीलो",
    name_en: "Asparagus",
    slug: "asparagus",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "न्यूरो",
    name_en: "Fiddlehead Fern",
    slug: "fiddlehead-fern",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "ब्रोकाउली",
    name_en: "Broccoli",
    slug: "broccoli",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "चुकुन्दर",
    name_en: "Beetroot",
    slug: "beetroot",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सजिवन",
    name_en: "Moringa",
    slug: "moringa",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "रातो बन्दा",
    name_en: "Red Cabbage",
    slug: "red-cabbage",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "जिरीको साग",
    name_en: "Dill Leaf",
    slug: "dill-leaf",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सेलरी",
    name_en: "Celery",
    slug: "celery",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "पार्सले",
    name_en: "Parsley",
    slug: "parsley",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "सौफको साग",
    name_en: "Fennel Greens",
    slug: "fennel-greens",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "पुदीना",
    name_en: "Mint",
    slug: "mint",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गान्टे मूला",
    name_en: "Turnip",
    slug: "turnip",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "इमली",
    name_en: "Tamarind",
    slug: "tamarind",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "तामा",
    name_en: "Bamboo Shoot",
    slug: "bamboo-shoot",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "तोफु",
    name_en: "Tofu",
    slug: "tofu",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "गुन्दुक",
    name_en: "Gundruk",
    slug: "gundruk",
    unit: "kg",
    category: "vegetable",
  },
  // ─── Fruits ──────────────────────────────────────────────────────────────
  {
    name_ne: "स्याउ(फूजी)",
    name_en: "Apple (Fuji)",
    slug: "apple-fuji",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "केरा(नेपाली)",
    name_en: "Banana (Nepali)",
    slug: "banana-nepali",
    unit: "dozen",
    category: "fruit",
  },
  {
    name_ne: "केरा(मालभोग)",
    name_en: "Banana (Malbhog)",
    slug: "banana-malbhog",
    unit: "dozen",
    category: "fruit",
  },
  {
    name_ne: "कागती",
    name_en: "Lime",
    slug: "lime",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "अनार",
    name_en: "Pomegranate",
    slug: "pomegranate",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "आँप(मालदह)",
    name_en: "Mango (Malda)",
    slug: "mango-malda",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "आँप(दसहरी)",
    name_en: "Mango (Dashehari)",
    slug: "mango-dashehari",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "तरबुजा(हरियो)",
    name_en: "Watermelon (Green)",
    slug: "watermelon-green",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "जुनार",
    name_en: "Mandarin Orange",
    slug: "mandarin-orange",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "भुई कटहर",
    name_en: "Jackfruit (Ground)",
    slug: "jackfruit-ground",
    unit: "piece",
    category: "fruit",
  },
  {
    name_ne: "काक्रो(लोकल)",
    name_en: "Cucumber (Local)",
    slug: "cucumber-local",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "काक्रो(हाइब्रीड)",
    name_en: "Cucumber (Hybrid)",
    slug: "cucumber-hybrid",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "काक्रो(लोकलक्रस)",
    name_en: "Cucumber (Local Cross)",
    slug: "cucumber-local-cross",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "रुख कटहर",
    name_en: "Jackfruit (Tree)",
    slug: "jackfruit-tree",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "नासपाती(चाइनिज)",
    name_en: "Pear (Chinese)",
    slug: "pear-chinese",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "मेवा(नेपाली)",
    name_en: "Papaya (Nepali)",
    slug: "papaya-nepali",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "मेवा(भारतीय)",
    name_en: "Papaya (Indian)",
    slug: "papaya-indian",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "लीच्ची(लोकल)",
    name_en: "Lychee (Local)",
    slug: "lychee-local",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "लीच्ची(भारतीय)",
    name_en: "Lychee (Indian)",
    slug: "lychee-indian",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "नरिवल(काँचो)",
    name_en: "Coconut (Raw)",
    slug: "coconut-raw",
    unit: "kg",
    category: "fruit",
  },
  {
    name_ne: "नरिवल(हरियो)",
    name_en: "Coconut (Green)",
    slug: "coconut-green",
    unit: "kg",
    category: "fruit",
  },
  // ─── Spices / Condiments (categorized as vegetable per Kalimati's grouping)
  {
    name_ne: "अदुवा",
    name_en: "Ginger",
    slug: "ginger",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खु्र्सानी सुकेको",
    name_en: "Dried Chili",
    slug: "dried-chili",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो(लाम्चो)",
    name_en: "Green Chili (Long)",
    slug: "green-chili-long",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो(बुलेट)",
    name_en: "Green Chili (Bullet)",
    slug: "green-chili-bullet",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो(माछे)",
    name_en: "Green Chili (Mache)",
    slug: "green-chili-mache",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "खुर्सानी हरियो(अकबरे)",
    name_en: "Green Chili (Akbare)",
    slug: "green-chili-akbare",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "भेडे खु्र्सानी",
    name_en: "Capsicum",
    slug: "capsicum",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "लसुन हरियो",
    name_en: "Garlic (Green)",
    slug: "garlic-green",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "हरियो धनिया",
    name_en: "Coriander Leaf",
    slug: "coriander-leaf",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "लसुन सुकेको चाइनिज",
    name_en: "Garlic Dry (Chinese)",
    slug: "garlic-dry-chinese",
    unit: "kg",
    category: "vegetable",
  },
  {
    name_ne: "लसुन सुकेको नेपाली",
    name_en: "Garlic Dry (Nepali)",
    slug: "garlic-dry-nepali",
    unit: "kg",
    category: "vegetable",
  },
  // ─── Fish ────────────────────────────────────────────────────────────────
  {
    name_ne: "माछा सुकेको",
    name_en: "Dried Fish",
    slug: "fish-dried",
    unit: "kg",
    category: "fish",
  },
  {
    name_ne: "ताजा माछा(रहु)",
    name_en: "Fresh Fish (Rohu)",
    slug: "fish-rohu",
    unit: "kg",
    category: "fish",
  },
  {
    name_ne: "ताजा माछा(बचुवा)",
    name_en: "Fresh Fish (Bachwa)",
    slug: "fish-bachwa",
    unit: "kg",
    category: "fish",
  },
  {
    name_ne: "ताजा माछा(छडी)",
    name_en: "Fresh Fish (Chhadi)",
    slug: "fish-chhadi",
    unit: "kg",
    category: "fish",
  },
];

// ─── Build a lookup map: cleaned Nepali name → CommodityDef ─────────────────
// Used by the scraper to match incoming names from the HTML table.
export const COMMODITY_MAP = new Map<string, CommodityDef>(
  COMMODITIES.map((c) => [c.name_ne, c])
);

// ─── Quick invariant check (runs at module load, not at runtime) ─────────────
if (process.env.NODE_ENV !== "production") {
  const slugs = COMMODITIES.map((c) => c.slug);
  const uniqueSlugs = new Set(slugs);
  if (uniqueSlugs.size !== slugs.length) {
    throw new Error("commodityMap: duplicate slugs detected — fix immediately");
  }
  const names = COMMODITIES.map((c) => c.name_ne);
  const uniqueNames = new Set(names);
  if (uniqueNames.size !== names.length) {
    throw new Error(
      "commodityMap: duplicate name_ne entries detected — fix immediately"
    );
  }
}
